
version: "3.3"
services:

  jenkins:
    image: vladquinn/jenkins:1.00
    ports:
      - 8089:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - net
    restart: on-failure

  tomcat:
    image: tomcat:8.5.16-jre8-alpine
    command: catalina.sh run
    ports:
      - 8087:8080
    container_name: tomcat
    networks:
      - net
    volumes:
      - ./config/tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./config/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./config/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    restart: on-failure

  sonarqube:
    user: root
    image: sonarqube:7.9.3-community
    ports:
      - 9000:9000
    container_name: sonarqube
    networks:
      - net
    volumes:
      - ./config/sonarqube/data/sonar.h2.db:/opt/sonarqube/data/sonar.h2.db
    restart: on-failure

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.17.0
    ports:
      - 8081:8081
    container_name: artifactory
    networks:
      - net
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    container_name: nginx
    networks:
      - net
    user: root
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/hosts:/etc/hosts
    restart: on-failure

  mysql:
    image: mysql:8.0
    networks:
      - net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=farm
    container_name: mysql
    ports:
      - 3308:3306
    restart: on-failure

  ldap:
    image: osixia/openldap:latest
    networks:
      - net
    ports:
      - 389:389
      - 636:636
    container_name: ldap
    volumes:
      - ./config/ldap/ldap-data.ldif:/my/ldap-data.ldif
    restart: on-failure

networks:
  net:
    driver: bridge


