
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - 8088:8080
    container_name: app
    networks:
      - net

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8089:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - net

  tomcat:
    image: tomcat:8.5.16-jre8-alpine
    command: catalina.sh run
    ports:
      - 8087:8080
    container_name: tomcat
    networks:
      - net

  sonarqube:
    image: library/sonarqube:latest
    ports:
      - 9000:9000
    container_name: sonarqube
    networks:
      - net
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - 8081:8081
    container_name: artifactory
    networks:
      - net

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    container_name: nginx
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
