
version: "3.3"
services:

  jenkins:
    image: vladquinn/jenkins:1.00
    ports:
      - 8089:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - net
    restart: on-failure

  tomcat:
    image: tomcat:8.5.16-jre8-alpine
    command: catalina.sh run
    ports:
      - 8087:8080
    container_name: tomcat
    networks:
      - net
    volumes:
      - ./config/tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./config/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./config/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    restart: on-failure

  sonarqube:
    image: vladquinn/sonarqube:latest
    ports:
      - 9000:9000
    container_name: sonarqube
    networks:
      - net
    restart: on-failure

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.17.0
    ports:
      - 8081:8081
    container_name: artifactory
    networks:
      - net
    restart: on-failure

  mysql:
    image: mysql:8.0
    networks:
      - net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=farm
    container_name: mysql
    ports:
      - 3308:3306
    restart: on-failure

  ldap:
    image: osixia/openldap:latest
    networks:
      - net
    ports:
      - 389:389
      - 636:636
    container_name: ldap
    volumes:
      - ./config/ldap/ldap-data.ldif:/my/ldap-data.ldif
    restart: on-failure

  oauth-server:
    build:
      context: ./oauth/
      dockerfile: Dockerfile
    image: oauth-server
    ports:
      - 8981:8981
    container_name: oauth-server
    networks:
      - net
    restart: on-failure

  angular:
    build:
      context: ./angular/
      dockerfile: Dockerfile
    image: angular
    ports:
      - 4200:4200
    container_name: angular
    networks:
      - net
    restart: on-failure
    command: ng serve --host 0.0.0.0 --port 4200

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    ports:
      - 8161:8161
      - 61616:61616
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    networks:
      - net
    restart: on-failure

  nginx-aws-ec2:
    image: nginx:mainline-alpine
    container_name: nginx-aws-ec2
    ports:
      - 80:80
    networks:
      - net
    restart: unless-stopped
    volumes:
      - ./config/nginx/aws-ec2/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/aws-ec2/certbot/conf:/etc/letsencrypt
      - ./config/nginx/aws-ec2/certbot/var:/var/lib/letsencrypt
      - ./config/nginx/aws-ec2/web-root:/var/www/html

  certbot-aws-ec2:
    container_name: certbot-aws-ec2
    image: certbot/certbot:v1.5.0
    networks:
      - net
    volumes:
      - ./config/nginx/aws-ec2/certbot/conf:/etc/letsencrypt
      - ./config/nginx/aws-ec2/certbot/var:/var/lib/letsencrypt
      - ./config/nginx/aws-ec2/web-root:/var/www/html
    depends_on:
      - nginx-aws-ec2
    command: certonly --webroot --webroot-path=/var/www/html --email vladquinn2010@gmail.com --agree-tos --no-eff-email --force-renewal -d oauth.xfarm.xyz

networks:
  net:
    driver: bridge


